In [3]:
#pip install numpy

In [1]:
import numpy as np

# numpy
numpy i.e., numarical python is a powerfull python library used for numerical computation it provides support for creating and manupulating large multidimensional arrays and matrices as well as has a wide collection of mathematical functions to operate on these arrays efficiently 
# Array
arrays are a collection of elements that are stored in a continuous block of memory, It can hold multiple values where all the values are of same datatype and allows efficient storage and computation

# Advantages of numpy
it is implemented in C language
making operations
highly optimize
it is faster than python list
it can perform advanced operations like slicing, reshaping and other mathematical computation like linear algebra, fourier transform, etc.
It consumes less memory as compared to python list
it integrates well with other libraries such as pandas, matplotlib, etc.

In [11]:
l=[1,2,3,4]
print(type(l))
print(l*3) #repeat the elements of list l for 3 times----------concatenation

m=[i*3 for i in l]
m

<class 'list'>
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


[3, 6, 9, 12]

In [12]:
n=np.array(l)  #array-----------
print(type(n))
print(n*3)

<class 'numpy.ndarray'>
[ 3  6  9 12]


In [15]:
l=["A","B","C"]
n=np.array(l)  #array-----------
print(n)
print(type(n))
#print(n*3) #error can't perform multiplication or any mathematical operation with string values--numpy array works on numbers and not on mixed datatypes

['A' 'B' 'C']
<class 'numpy.ndarray'>


In [2]:
n=np.array([[1,2,3],[4,5,6]])
print(n)
print(type(n))
print("Shape ", n.shape)
print("Dimension ",n.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Shape  (2, 3)
Dimension  2


### Broadcasting

In [4]:
n=np.array([1,2,3,4,5])
print(n*3) #array access all the elements and perform operation without loops

[ 3  6  9 12 15]


In [6]:
n=np.array([[1,2,3],[4,5,6]])
m=np.array([10,20,30])
print(n+m)

[[11 22 33]
 [14 25 36]]


In [7]:
n=np.zeros((2,3))  #array of zeros
print(n)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
n=np.ones((2,3))  #array of ones
print(n)

[[1. 1. 1.]
 [1. 1. 1.]]


### random number

In [17]:
n=np.random.rand()  # random float number between 0-1
#n
n=np.random.rand(3 ,3)  # 3,3 array of random float number between 0-1
n

array([[0.52326189, 0.04556614, 0.40502251],
       [0.24749069, 0.93909562, 0.31914237],
       [0.90138979, 0.51644767, 0.96409978]])

In [21]:
n=np.random.randint(1,10)  # random integer between 1-10
n

6

In [24]:
n=np.random.randint(1,10,size=(3,2)) # 2,3 array of any random integer between 1-10
n

array([[6, 6],
       [9, 5],
       [3, 1]])

In [27]:
n=np.array([[1,2,3],[4,5,6]])
print("Shape of n ", n.shape)
print(n)
m=n.T                         #-----------Transpose
print("Shape of m ", m.shape)
print(m)

Shape of n  (2, 3)
[[1 2 3]
 [4 5 6]]
Shape of m  (3, 2)
[[1 4]
 [2 5]
 [3 6]]


### reshape(row,col)

In [43]:
n=np.array([[1,2,3],[4,5,6]])
print(n.reshape(6,1))
print("---------------------")
print(n.reshape(3,2))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
---------------------
[[1 2]
 [3 4]
 [5 6]]


### concatenate and stack

In [38]:
n=np.array([1,2,3,4,5,6]).reshape(2,3)  #method re-chaining
m=np.array([7,8,9,1,2,3]).reshape(2,3)
a=np.concatenate((n,m),axis=0)        #----axis=0//vertically append------creating stack
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
(4, 3)


In [39]:
a=np.concatenate((n,m),axis=1)  #----axis=1 //Horizontally append----side by side 
print(a)
print(a.shape)

[[1 2 3 7 8 9]
 [4 5 6 1 2 3]]
(2, 6)


In [42]:
n=np.array([1,2,3,4,5,6]).reshape(2,3)
m=np.array([7,8,9,1,2,3]).reshape(2,3)
a=np.vstack((n,m))        #-----------------stacking vertically
print(a)
b=np.hstack((n,m))        #-----------------stacking Horizontally
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 2 3 7 8 9]
 [4 5 6 1 2 3]]


### Typecasting of array

In [44]:
n=np.array([1,2,3,4,5,6],dtype="float").reshape(2,3)
n

array([[1., 2., 3.],
       [4., 5., 6.]])

### methods or function

In [46]:
n=np.array([1,2,3])
print(n)
a=np.append(n,[4,5,6,3])     #-----append array into array n
print(a)
i=np.insert(a,1,[10,20,34])  #-----insert array at the gven index
print(i)
d=np.delete(i,[3,4,5])       #-----delete elements from the array at the gven index
print(d)

[1 2 3]
[1 2 3 4 5 6 3]
[ 1 10 20 34  2  3  4  5  6  3]
[ 1 10 20  4  5  6  3]


In [49]:
n=np.arange(1,20,2).reshape(5,2)  #aramge-- sane as range function
print(n)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


### Indexing and Slicing

In [54]:
n=np.arange(20,30).reshape(5,2)  #aramge-- sane as range function
print(n)
print(n[3,1])
print(n[2][1])   # Indexing--------------

[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
27
25


In [59]:
n=np.arange(1,31).reshape(5,6)  #aramge-- sane as range function
print(n)
print(n[1:4,0:3])  #=slicing

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 7  8  9]
 [13 14 15]
 [19 20 21]]


### ----------

In [66]:
b=np.arange(1,7)
print(b)
print(b.sum(),b.mean(),b.std(),b.var(),b.prod(),b.max(),b.min(),b.cumsum())

[1 2 3 4 5 6]
21 3.5 1.707825127659933 2.9166666666666665 720 6 1 [ 1  3  6 10 15 21]
